<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Version>1.0.0</Version>
        <AssemblyVersion>1.0.0.0</AssemblyVersion>
        <FileVersion>1.0.0.0</FileVersion>
        <Authors>Noctusoft</Authors>
        <Description>A lightweight, local key vault implementation for .NET applications that replicates Azure Key Vault functionality for local development environments.</Description>
        <PackageTags>configuration;keyvault;secrets;development</PackageTags>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="../../README.md" Pack="true" PackagePath="/" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.4.0" />
        <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.7.0" />
        <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
        <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
        <PackageReference Include="Microsoft.AspNetCore.Http.Extensions" Version="2.3.0" />
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.4" />
    </ItemGroup>

</Project>