<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <Description>A utility library that simplifies using either Azure Key Vault or local key vault based on environment conditions.</Description>
        <PackageTags>configuration;azure;keyvault;secrets;development</PackageTags>
        <Version>1.0.1</Version>
        <PackageVersion>1.0.1</PackageVersion>
        <AssemblyVersion>1.0.1.0</AssemblyVersion>
        <FileVersion>1.0.1.0</FileVersion>
        <Authors>Noctusoft</Authors>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="../../README.md" Pack="true" PackagePath="/" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.7.0" />
        <PackageReference Include="Azure.Identity" Version="1.10.4" />
        <PackageReference Include="Microsoft.Extensions.Configuration.AzureKeyVault" Version="3.1.24" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.4" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.4" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Noctusoft.EzLocalKeyVault\Noctusoft.EzLocalKeyVault.csproj" />
    </ItemGroup>

</Project>